import { buildCommitValidityPolicy } from '@kontourai/surface';

export const SURFACE_TRUST_POLICIES = {
  affectedSurface: buildCommitValidityPolicy({
    id: 'veritas.surface',
    claimType: 'veritas-affected-surface',
    requiredEvidence: ['policy_rule'],
    requiredMethods: ['auditability'],
    requiresCorroboration: false,
    requiredProof: ['veritas evidence artifact'],
    reviewAuthority: 'veritas',
    stalenessTriggers: ['source_ref changes', 'affected node changes'],
    conflictRules: ['newer evidence for the same node supersedes older evidence'],
    impactLevel: 'medium',
  }),
  proofLane: buildCommitValidityPolicy({
    id: 'veritas.proof-lane',
    claimType: 'software-proof',
    requiredEvidence: ['test_output'],
    requiredMethods: ['validation'],
    requiresCorroboration: false,
    requiredProof: ['selected proof command'],
    reviewAuthority: 'veritas',
    stalenessTriggers: ['source_ref changes', 'proof command changes', 'baseline proof fails'],
    conflictRules: ['failed proof rejects a previously verified proof claim'],
    impactLevel: 'high',
  }),
  policyResult: buildCommitValidityPolicy({
    id: 'veritas.policy-result',
    claimType: 'veritas-policy-result',
    requiredEvidence: ['policy_rule'],
    requiredMethods: ['validation'],
    requiresCorroboration: false,
    requiredProof: ['policy pack evaluation'],
    reviewAuthority: 'veritas policy pack',
    stalenessTriggers: ['source_ref changes', 'policy pack changes', 'rule implementation changes'],
    conflictRules: ['blocking failed rules reject the affected policy claim'],
    impactLevel: 'high',
  }),
  proofFamily: {
    id: 'veritas.proof-family',
    claimType: 'veritas-proof-family',
    requiredEvidence: ['policy_rule'],
    requiredMethods: ['validation'],
    requiresCorroboration: false,
    requiredProof: ['proof-family manifest'],
    reviewAuthority: 'veritas proof family owner',
    validityRule: { kind: 'duration', durationDays: 7 },
    stalenessTriggers: ['review trigger changes', 'freshness status changes', 'catch evidence changes'],
    conflictRules: ['stale or unknown proof families dispute promotion readiness'],
    impactLevel: 'medium',
  },
  verificationBudget: buildCommitValidityPolicy({
    id: 'veritas.verification-budget',
    claimType: 'veritas-verification-budget',
    requiredEvidence: ['policy_rule'],
    requiredMethods: ['auditability'],
    requiresCorroboration: false,
    requiredProof: ['verification budget'],
    reviewAuthority: 'veritas',
    stalenessTriggers: ['proof family inventory changes', 'proof lane inventory changes'],
    conflictRules: ['unknown or stale proof families dispute budget readiness'],
    impactLevel: 'medium',
  }),
  externalToolResult: buildCommitValidityPolicy({
    id: 'veritas.external-tool-result',
    claimType: 'veritas-external-tool-result',
    requiredEvidence: ['test_output'],
    requiredMethods: ['auditability'],
    requiresCorroboration: false,
    requiredProof: ['external tool artifact'],
    reviewAuthority: 'external tool plus veritas adapter',
    stalenessTriggers: ['source_ref changes', 'external tool artifact changes'],
    conflictRules: ['blocking external tool failures reject the affected tool claim'],
    impactLevel: 'medium',
  }),
  proposal: {
    id: 'veritas.proposal',
    claimType: 'veritas-proposal',
    requiredEvidence: ['policy_rule'],
    requiredMethods: ['auditability'],
    requiresCorroboration: false,
    requiredProof: ['eval proposal artifact'],
    reviewAuthority: 'human reviewer',
    validityRule: { kind: 'manual' },
    stalenessTriggers: ['proposal accepted', 'proposal rejected', 'supporting eval history changes'],
    conflictRules: ['rejected proposals supersede proposed claims'],
    impactLevel: 'medium',
  },
};
