import { buildCommitValidityPolicy } from '@kontourai/surface';

export const SURFACE_TRUST_POLICIES = {
  affectedSurface: buildCommitValidityPolicy({
    id: 'veritas.surface',
    claimType: 'veritas-affected-surface',
    requiredEvidence: ['policy_rule'],
    requiredMethods: ['auditability'],
    requiresCorroboration: false,
    acceptanceCriteria: ['veritas evidence artifact'],
    reviewAuthority: 'veritas',
    stalenessTriggers: ['source_ref changes', 'affected node changes'],
    conflictRules: ['newer evidence for the same node supersedes older evidence'],
    impactLevel: 'medium',
  }),
  evidenceCheck: buildCommitValidityPolicy({
    id: 'veritas.evidence-check',
    claimType: 'software-evidence-check',
    requiredEvidence: ['test_output'],
    requiredMethods: ['validation'],
    requiresCorroboration: false,
    acceptanceCriteria: ['selected evidenceCheck command'],
    reviewAuthority: 'veritas',
    stalenessTriggers: ['source_ref changes', 'evidenceCheck command changes', 'baseline evidenceCheck fails'],
    conflictRules: ['failed evidenceCheck rejects a previously verified evidenceCheck claim'],
    impactLevel: 'high',
  }),
  policyResult: buildCommitValidityPolicy({
    id: 'veritas.policy-result',
    claimType: 'veritas-policy-result',
    requiredEvidence: ['policy_rule'],
    requiredMethods: ['validation'],
    requiresCorroboration: false,
    acceptanceCriteria: ['requirements evaluation'],
    reviewAuthority: 'veritas requirements',
    stalenessTriggers: ['source_ref changes', 'Repo Standards changes', 'requirement implementation changes'],
    conflictRules: ['blocking failed requirements reject the affected claim'],
    impactLevel: 'high',
  }),
  evidenceInventory: {
    id: 'veritas.evidence-inventory',
    claimType: 'veritas-evidence-inventory',
    requiredEvidence: ['policy_rule'],
    requiredMethods: ['validation'],
    requiresCorroboration: false,
    acceptanceCriteria: ['evidenceCheck inventory'],
    reviewAuthority: 'veritas evidence owner',
    validityRule: { kind: 'duration', durationDays: 7 },
    stalenessTriggers: ['review trigger changes', 'freshness status changes', 'catch evidence changes'],
    conflictRules: ['stale or unknown evidence inventories dispute promotion readiness'],
    impactLevel: 'medium',
  },
  readinessCoverage: buildCommitValidityPolicy({
    id: 'veritas.readiness-coverage',
    claimType: 'veritas-readiness-coverage',
    requiredEvidence: ['policy_rule'],
    requiredMethods: ['auditability'],
    requiresCorroboration: false,
    acceptanceCriteria: ['readiness coverage'],
    reviewAuthority: 'veritas',
    stalenessTriggers: ['evidence inventory changes', 'evidenceCheck inventory changes'],
    conflictRules: ['unknown or stale evidence inventories dispute readiness coverage'],
    impactLevel: 'medium',
  }),
  externalToolResult: buildCommitValidityPolicy({
    id: 'veritas.external-tool-result',
    claimType: 'veritas-external-tool-result',
    requiredEvidence: ['test_output'],
    requiredMethods: ['auditability'],
    requiresCorroboration: false,
    acceptanceCriteria: ['external tool artifact'],
    reviewAuthority: 'external tool plus Veritas Repo Map',
    stalenessTriggers: ['source_ref changes', 'external tool artifact changes'],
    conflictRules: ['blocking external tool failures reject the affected tool claim'],
    impactLevel: 'medium',
  }),
  recommendation: {
    id: 'veritas.recommendation',
    claimType: 'veritas-recommendation',
    requiredEvidence: ['policy_rule'],
    requiredMethods: ['auditability'],
    requiresCorroboration: false,
    acceptanceCriteria: ['standards feedback artifact'],
    reviewAuthority: 'human reviewer',
    validityRule: { kind: 'manual' },
    stalenessTriggers: ['recommendation accepted', 'recommendation rejected', 'supporting standards feedback changes'],
    conflictRules: ['rejected recommendations supersede proposed claims'],
    impactLevel: 'medium',
  },
  governanceArtifact: {
    id: 'veritas.governance-artifact',
    claimType: 'veritas-governance-artifact',
    requiredEvidence: ['attestation', 'policy_rule'],
    requiredMethods: ['auditability', 'attestation'],
    requiresCorroboration: false,
    acceptanceCriteria: ['Protected Standards hash inspection', 'authority attestation status'],
    reviewAuthority: 'veritas plus authority attestation',
    validityRule: { kind: 'manual' },
    stalenessTriggers: ['Repo Standards hash changes', 'Repo Map hash changes', 'authority settings hash changes', 'attestation expiry'],
    conflictRules: ['hash drift disputes Protected Standards currency'],
    impactLevel: 'high',
  },
};
