import { mkdirSync, writeFileSync, appendFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  generateEvalDraft,
  generateVeritasReport,
  inspectRuntimeAdapterStatus,
} from '../src/index.mjs';

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const timestamp = new Date().toISOString();
const compactStamp = timestamp.replace(/[:.]/g, '-');
const runId = process.env.VERITAS_RUN_ID ?? `veritas-checkin-${compactStamp}`;
const summaryPath = process.env.GITHUB_STEP_SUMMARY;

function summarizePolicyResults(policyResults) {
  return {
    passed: policyResults.filter((result) => result.passed === true).length,
    failed: policyResults.filter((result) => result.passed === false).length,
    metadata_only: policyResults.filter((result) => result.passed === null).length,
  };
}

function writeArtifact(relativePath, content) {
  const outputPath = resolve(rootDir, relativePath);
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, content, 'utf8');
}

const report = generateVeritasReport(
  {
    rootDir,
    workingTree: true,
    runId,
    baselineCiFastStatus: 'success',
  },
  { rootDir },
);

const draft = generateEvalDraft(
  {
    rootDir,
    evidencePath: report.artifactPath,
    force: true,
    reviewerConfidence: 'unknown',
    overrideCount: 0,
    notes: [
      'Automated dogfood check-in generated by scripts/dogfood-checkin.mjs.',
      'Use this draft when you want to convert the automated snapshot into a human-scored eval record.',
    ],
  },
  { rootDir },
);

const runtimeStatus = inspectRuntimeAdapterStatus(rootDir);
const policySummary = summarizePolicyResults(report.record.policy_results);

const checkin = {
  version: 1,
  generated_at: timestamp,
  run_id: runId,
  report_artifact_path: report.artifactPath,
  eval_draft_artifact_path: draft.artifactPath,
  suggested_eval_command: draft.suggestedRecordCommand,
  source_kind: report.record.source_kind,
  source_scope: report.record.source_scope,
  unresolved_files_count: report.record.unresolved_files.length,
  affected_nodes: report.record.affected_nodes,
  affected_lanes: report.record.affected_lanes,
  selected_proof_commands: report.record.selected_proof_commands,
  uncovered_path_result: report.record.uncovered_path_result,
  policy_results_summary: policySummary,
  runtime_status: runtimeStatus,
};

const markdown = [
  '## Veritas Dogfood Check-in',
  '',
  `- **Run ID:** ${runId}`,
  `- **Generated at:** ${timestamp}`,
  `- **Report artifact:** \`${report.artifactPath}\``,
  `- **Eval draft artifact:** \`${draft.artifactPath}\``,
  `- **Source:** ${report.record.source_kind} (${report.record.source_scope.join(', ')})`,
  `- **Unresolved files:** ${report.record.unresolved_files.length}`,
  `- **Policy results:** ${policySummary.passed} passed, ${policySummary.failed} failed, ${policySummary.metadata_only} metadata-only`,
  `- **Selected proof commands:** \`${report.record.selected_proof_commands.join(', ') || 'none'}\``,
  `- **Next commands:** ${runtimeStatus.nextCommands.length > 0 ? runtimeStatus.nextCommands.join(' | ') : 'none'}`,
  '',
  '### Suggested Eval Command',
  '',
  `\`${draft.suggestedRecordCommand}\``,
  '',
].join('\n');

writeArtifact(
  `.veritas/checkins/${runId}.json`,
  `${JSON.stringify(checkin, null, 2)}\n`,
);
writeArtifact(`.veritas/checkins/${runId}.md`, `${markdown}\n`);

if (summaryPath) {
  appendFileSync(summaryPath, `${markdown}\n`, 'utf8');
}

process.stdout.write(
  `${JSON.stringify(
    {
      runId,
      reportArtifactPath: report.artifactPath,
      evalDraftArtifactPath: draft.artifactPath,
      checkinJsonPath: `.veritas/checkins/${runId}.json`,
      checkinMarkdownPath: `.veritas/checkins/${runId}.md`,
      policyResultsSummary: policySummary,
      runtimeStatus,
      suggestedEvalCommand: draft.suggestedRecordCommand,
    },
    null,
    2,
  )}\n`,
);
