import {
  appendFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from 'node:fs';
import { createHash } from 'node:crypto';
import { basename, dirname, relative, resolve } from 'node:path';
import { execFileSync } from 'node:child_process';
import {
  loadJson,
  loadAdapterConfig,
  loadPolicyPack,
  loadTeamProfile,
  loadEvidenceArtifact,
  loadEvalDraftArtifact,
  loadMarkerBenchmarkScenario,
  loadMarkerBenchmarkTranscript,
  loadMarkerBenchmarkSuite,
} from './load.mjs';
import {
  parseTokens,
  parseArgs,
  parseBudgetArgs,
  parseInitArgs,
  parseAttestArgs,
  parsePrintArgs,
  parseApplyArgs,
  parsePreToolUseArgs,
  parseEvalArgs,
  parseMarkerEvalArgs,
  parseMarkerSuiteEvalArgs,
  parseShadowArgs,
} from './args.mjs';
import { assertWithinDir, normalizeRepoPath, relativeRepoPath } from './paths.mjs';
import {
  slugifyProjectName,
  inferBootstrapRepoInsights,
  buildStarterAdapter,
  buildStarterPolicyPack,
  buildStarterTeamProfile,
  buildBootstrapReadme,
  writeBootstrapStarterKit,
  buildSuggestedPackageScripts,
  buildSuggestedCiSnippet,
} from './bootstrap.mjs';
import {
  buildInitRecommendation,
  applyInitRecommendation,
} from './bootstrap/recommendation.mjs';
import { shellQuote, runProofCommand, resolveGitHead, stagedDiffSha256 } from './shell.mjs';
import {
  buildSuggestedGitHook,
  buildSuggestedRuntimeHook,
  buildSuggestedStopHook,
  buildSuggestedCodexHookConfig,
  buildSuggestedClaudeCodePreToolUseHook,
  buildSuggestedClaudeCodePostSessionHook,
  inspectCodexHookTarget,
  applyPackageScripts,
  applyCiSnippet,
  applyGitHook,
  applyRuntimeHook,
  applyStopHook,
  inspectRuntimeAdapterStatus,
  applyCodexHook,
  applyClaudeCodePreToolUseHook,
  applyClaudeCodePostSessionHook,
  evaluatePreToolUse,
} from './hooks.mjs';
import {
  applyGovernanceBlocks,
  buildGovernanceBlock,
} from './governance.mjs';
import {
  buildSurfaceTrustInput,
  validateSurfaceTrustInputAtBoundary,
} from './surface/projection.mjs';
import {
  scoreMarkerBenchmarkCondition,
  compareMarkerBenchmarkRuns,
  buildMarkerBenchmarkSuiteReport,
  generateMarkerBenchmarkComparison,
  generateMarkerBenchmarkSuiteReport,
} from './eval/marker-benchmark.mjs';
import {
  buildEvalRecord,
  buildEvalDraft,
  buildEvalRecordCommand,
  validateEvalDraftContext,
  writeEvalArtifact,
  appendEvalHistory,
  writeEvalDraftArtifact,
} from './eval/loop.mjs';
import {
  readProofRoutes,
  readProofs,
  readDefaultProofIds,
  readRequiredProofIds,
  commandsForProofIds,
  proofRecordsForCommands,
  loadProofSuiteResults,
  buildVerificationBudget,
  buildExternalToolResults,
  readUncoveredPathPolicy,
  routeMatchesAnyComponent,
  serializeProofRoutes,
} from './proof/index.mjs';
import {
  buildCodexEvalDraft,
  observeCodexEval,
} from './integrations/codex/eval-capture.mjs';
import { classifyNodes } from './repo/classify.mjs';
import { matchesPatterns, matchesPatternsForAnyFile } from './util/patterns.mjs';
import { uniqueStrings } from './util/strings.mjs';
import {
  resolveProofPlan,
  resolveWorkstream,
  parseBaselineCiFastStatus,
  formatTriState,
  buildEvidenceRecord,
  writeEvidenceArtifact,
  writeSurfaceClaimInputs,
  listChangedFiles,
  listWorkingTreeFiles,
  resolveReportInputs,
  buildMarkdownSummary,
  feedbackStatusForPolicyResult,
  buildFeedbackSummary,
  feedbackHasFailures,
  buildEvalMarkdownSummary,
  buildEvalDraftMarkdownSummary,
  mergeEvalRecordOptions,
  resolveVeritasPaths,
  generateVeritasReport,
  resolveProofCommands,
} from './report.mjs';
import {
  evaluateRequiredArtifactsRule,
  evaluateGovernanceBlockRule,
  evaluateDiffRequiredRule,
  evaluateForbiddenPatternRule,
  evaluateRequiredPatternRule,
  evaluateHeaderRequiredRule,
  evaluateCrossSurfaceWriteRule,
  evaluatePolicyRule,
  evaluatePolicyPack,
  RULE_EVALUATORS,
} from './rules/evaluate.mjs';
import {
  buildExplainText,
  runExplainCli,
  checkBoundaries,
  runBoundariesCheckCli,
} from './explain.mjs';
import {
  generateEvalDraft,
  generateEvalRecord,
  generateEvalSummary,
} from './eval/records.mjs';
import {
  generateRuleProposals,
  generateAndWriteProposals,
  listProposals,
  loadProposal,
  applyProposal,
} from './proposals.mjs';
import {
  runVeritasReportCli,
  runVerificationBudgetCli,
  runInitCli,
  runPrintPackageScriptsCli,
  runPrintCiSnippetCli,
  runPrintGitHookCli,
  runPrintRuntimeHookCli,
  runPrintStopHookCli,
  runPrintClaudeCodePreToolUseHookCli,
  runPrintGovernanceBlockCli,
  runPrintCodexHookCli,
  runRuntimeStatusCli,
  runApplyPackageScriptsCli,
  runApplyCiSnippetCli,
  runApplyGitHookCli,
  runApplyRuntimeHookCli,
  runApplyStopHookCli,
  runApplyClaudeCodePreToolUseHookCli,
  runApplyGovernanceBlocksCli,
  runApplyCodexHookCli,
  runEvalRecordCli,
  runEvalSummaryCli,
  runEvalMarkerCli,
  runEvalMarkerSuiteCli,
  runEvalProposeCli,
  runEvalDraftCli,
  runEvalObserveCli,
  runProposalCli,
  runAttestCli,
  runClaudeCodePreToolUseCli,
  runIntegrationsCli,
  runShadowRunCli,
  runClaimCli,
} from './cli/index.mjs';
export * from './surface/projection.mjs';
export * from './surface/dashboard.mjs';
export * from './surface/extension.mjs';
export * from './claims/store.mjs';
export * from './claims/templates.mjs';
export * from './claims/init.mjs';

export {
  loadJson,
  loadAdapterConfig,
  loadPolicyPack,
  loadTeamProfile,
  loadEvidenceArtifact,
  loadEvalDraftArtifact,
  loadMarkerBenchmarkScenario,
  loadMarkerBenchmarkTranscript,
  loadMarkerBenchmarkSuite,
  parseTokens,
  parseArgs,
  parseBudgetArgs,
  parseInitArgs,
  parseAttestArgs,
  parsePrintArgs,
  parseApplyArgs,
  parsePreToolUseArgs,
  parseEvalArgs,
  parseMarkerEvalArgs,
  parseMarkerSuiteEvalArgs,
  parseShadowArgs,
  normalizeRepoPath,
  slugifyProjectName,
  inferBootstrapRepoInsights,
  buildStarterAdapter,
  buildStarterPolicyPack,
  buildStarterTeamProfile,
  buildBootstrapReadme,
  buildInitRecommendation,
  writeBootstrapStarterKit,
  applyInitRecommendation,
  buildSuggestedPackageScripts,
  buildSuggestedCiSnippet,
  buildSuggestedGitHook,
  buildSuggestedRuntimeHook,
  buildSuggestedStopHook,
  buildSuggestedCodexHookConfig,
  buildSuggestedClaudeCodePreToolUseHook,
  buildSuggestedClaudeCodePostSessionHook,
  inspectCodexHookTarget,
  buildGovernanceBlock,
  applyGovernanceBlocks,
  applyPackageScripts,
  applyCiSnippet,
  applyGitHook,
  applyRuntimeHook,
  applyStopHook,
  inspectRuntimeAdapterStatus,
  applyCodexHook,
  applyClaudeCodePreToolUseHook,
  applyClaudeCodePostSessionHook,
  evaluatePreToolUse,
  classifyNodes,
  matchesPatterns,
  matchesPatternsForAnyFile,
  uniqueStrings,
  evaluateRequiredArtifactsRule,
  evaluateGovernanceBlockRule,
  evaluateDiffRequiredRule,
  evaluateForbiddenPatternRule,
  evaluateRequiredPatternRule,
  evaluateHeaderRequiredRule,
  evaluateCrossSurfaceWriteRule,
  evaluatePolicyRule,
  evaluatePolicyPack,
  RULE_EVALUATORS,
  scoreMarkerBenchmarkCondition,
  compareMarkerBenchmarkRuns,
  buildMarkerBenchmarkSuiteReport,
  generateMarkerBenchmarkComparison,
  generateMarkerBenchmarkSuiteReport,
  buildEvalRecord,
  buildEvalDraft,
  buildEvalRecordCommand,
  validateEvalDraftContext,
  writeEvalArtifact,
  appendEvalHistory,
  writeEvalDraftArtifact,
  readProofRoutes,
  readProofs,
  readDefaultProofIds,
  readRequiredProofIds,
  commandsForProofIds,
  proofRecordsForCommands,
  loadProofSuiteResults,
  buildVerificationBudget,
  buildExternalToolResults,
  readUncoveredPathPolicy,
  routeMatchesAnyComponent,
  serializeProofRoutes,
  buildCodexEvalDraft,
  observeCodexEval,
  resolveProofPlan,
  resolveWorkstream,
  parseBaselineCiFastStatus,
  formatTriState,
  buildEvidenceRecord,
  writeEvidenceArtifact,
  writeSurfaceClaimInputs,
  listChangedFiles,
  listWorkingTreeFiles,
  resolveReportInputs,
  buildMarkdownSummary,
  feedbackStatusForPolicyResult,
  buildFeedbackSummary,
  feedbackHasFailures,
  buildEvalMarkdownSummary,
  buildEvalDraftMarkdownSummary,
  mergeEvalRecordOptions,
  resolveVeritasPaths,
  generateVeritasReport,
  resolveProofCommands,
  buildExplainText,
  runExplainCli,
  checkBoundaries,
  runBoundariesCheckCli,
  generateEvalDraft,
  generateEvalRecord,
  generateEvalSummary,
  generateRuleProposals,
  generateAndWriteProposals,
  listProposals,
  loadProposal,
  applyProposal,
  runVeritasReportCli,
  runVerificationBudgetCli,
  runInitCli,
  runPrintPackageScriptsCli,
  runPrintCiSnippetCli,
  runPrintGitHookCli,
  runPrintRuntimeHookCli,
  runPrintStopHookCli,
  runPrintClaudeCodePreToolUseHookCli,
  runPrintGovernanceBlockCli,
  runPrintCodexHookCli,
  runRuntimeStatusCli,
  runApplyPackageScriptsCli,
  runApplyCiSnippetCli,
  runApplyGitHookCli,
  runApplyRuntimeHookCli,
  runApplyStopHookCli,
  runApplyClaudeCodePreToolUseHookCli,
  runApplyGovernanceBlocksCli,
  runApplyCodexHookCli,
  runEvalRecordCli,
  runEvalSummaryCli,
  runEvalMarkerCli,
  runEvalMarkerSuiteCli,
  runEvalProposeCli,
  runEvalDraftCli,
  runEvalObserveCli,
  runProposalCli,
  runAttestCli,
  runClaudeCodePreToolUseCli,
  runIntegrationsCli,
  runShadowRunCli,
  runClaimCli,
};
export * from './attestations.mjs';
export * from './integrations/contract.mjs';
export * from './integrations/transcripts.mjs';
export * from './integrations/runtime-adapters.mjs';
export * from './eval/filesystem-observer.mjs';
export * from './eval/run-history.mjs';
export * from './proposals.mjs';
export * from './cli/plugins.mjs';
export * from './plugins/registry.mjs';
export * from './plugins/loader.mjs';
